spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    clean-disabled: false  # 개발환경에서만 clean 허용

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB

jwt:
  secret: ${JWT_SECRET}
  #  access-token-validity: 60000
  access-token-validity: 1800000
  refresh-token-validity: 604800000

logging:
  level:
    com.junwoo.hamkke: debug
    org.hibernate.sql: info
    org.springframework.security: info