spring:
  datasource:
    url: jdbc:tc:mysql:8.0.32:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

  h2:
    console:
      enabled: true

jwt:
  secret: test-jwt-secret-key-for-hs256-32bytes!
  access-token-validity: 60000
  refresh-token-validity: 120000

logging:
  level:
    root: warn

cors:
  allowed-origins: localhost:3000

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: test

admin:
  id: test
  password: test
  nickname: test

discord:
  webhook:
    url: test-discord-webhook-url