global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # =========================
  # Spring Boot (Blue / Green)
  # =========================
  - job_name: "spring-blue"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - blue:8080

  - job_name: "spring-green"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - green:8080

  # =========================
  # MySQL Exporter
  # =========================
  - job_name: "mysql"
    static_configs:
      - targets:
          - mysqld-exporter:9104